<?php

require_once 'D:\jules\code\zenino\core\ZeninoDiatonicToolkit.php';

/**
 * Test class for ZeninoDiatonicToolkit.
 * Generated by PHPUnit on 2010-12-28 at 22:47:06.
 */
class ZeninoDiatonicToolkitTest extends PHPUnit_Framework_TestCase
{
  /**
   * Sets up the fixture, for example, opens a network connection.
   * This method is called before a test is executed.
  protected function setUp()
   */
  {
  }

  /**
   * Tears down the fixture, for example, closes a network connection.
   * This method is called after a test is executed.
   */
  protected function tearDown()
  {
  }

  /**
   * @todo Implement testGetNotes().
   */
  public function testGetNotes()
  {
      // Remove the following lines when you implement this test.
      $this->markTestIncomplete(
        'This test has not been implemented yet.'
      );
  }

  /**
   * @todo Implement testIntToNote().
   */
  public function testIntToNote()
  {
      // Remove the following lines when you implement this test.
      $this->markTestIncomplete(
        'This test has not been implemented yet.'
      );
  }

  /**
   * @todo Implement testInterval().
   */
  public function testInterval()
  {
      // Remove the following lines when you implement this test.
      $this->markTestIncomplete(
        'This test has not been implemented yet.'
      );
  }
}
?>
