<?php
require_once dirname(__FILE__).'/../ZeninoLoader.php';
ZeninoLoader::register();

/**
 * Test class for ZeninoIntervalToolkit.
 * Generated by PHPUnit on 2010-12-28 at 18:28:19.
 */
class ZeninoIntervalToolkitTest extends PHPUnit_Framework_TestCase
{
  /**
   * Sets up the fixture, for example, opens a network connection.
   * This method is called before a test is executed.
   */
  protected function setUp()
  {
    
  }

  /**
   * Tears down the fixture, for example, closes a network connection.
   * This method is called after a test is executed.
   */
  protected function tearDown()
  {
  }

  /**
   * @todo Implement testUnison().
   */
  public function testUnison()
  {
      // Remove the following lines when you implement this test.
      $this->markTestIncomplete(
        'This test has not been implemented yet.'
      );
  }

  /**
   * @todo Implement testSecond().
   */
  public function testSecond()
  {
      // Remove the following lines when you implement this test.
      $this->markTestIncomplete(
        'This test has not been implemented yet.'
      );
  }

  /**
   * @todo Implement testThird().
   */
  public function testThird()
  {
      // Remove the following lines when you implement this test.
      $this->markTestIncomplete(
        'This test has not been implemented yet.'
      );
  }

  /**
   * @todo Implement testFourth().
   */
  public function testFourth()
  {
      // Remove the following lines when you implement this test.
      $this->markTestIncomplete(
        'This test has not been implemented yet.'
      );
  }

  /**
   * @todo Implement testFifth().
   */
  public function testFifth()
  {
      // Remove the following lines when you implement this test.
      $this->markTestIncomplete(
        'This test has not been implemented yet.'
      );
  }

  /**
   * @todo Implement testSixth().
   */
  public function testSixth()
  {
      // Remove the following lines when you implement this test.
      $this->markTestIncomplete(
        'This test has not been implemented yet.'
      );
  }

  /**
   * @todo Implement testSeventh().
   */
  public function testSeventh()
  {
      // Remove the following lines when you implement this test.
      $this->markTestIncomplete(
        'This test has not been implemented yet.'
      );
  }

  /**
   * @todo Implement testMinorUnison().
   */
  public function testMinorUnison()
  {
      // Remove the following lines when you implement this test.
      $this->markTestIncomplete(
        'This test has not been implemented yet.'
      );
  }

  /**
   * @todo Implement testMajorUnison().
   */
  public function testMajorUnison()
  {
      // Remove the following lines when you implement this test.
      $this->markTestIncomplete(
        'This test has not been implemented yet.'
      );
  }

  /**
   * @todo Implement testAugmentedUnison().
   */
  public function testAugmentedUnison()
  {
      // Remove the following lines when you implement this test.
      $this->markTestIncomplete(
        'This test has not been implemented yet.'
      );
  }

  /**
   * @dataProvider minorSecondProvider
   */
  public function testMinorSecond($note, $expected)
  {
    $result = ZeninoIntervalToolkit::minorSecond($note);
    $this->assertEquals($expected, $result);
  }
  public function minorSecondProvider()
  {
    return array(
      array('C', 'Db'), array('F#','G'), array('Bbb', 'Cbb'),
      array('G##', 'A#')
    );
  }

  /**
   * @todo Implement testMajorSecond().
   */
  public function testMajorSecond()
  {
      // Remove the following lines when you implement this test.
      $this->markTestIncomplete(
        'This test has not been implemented yet.'
      );
  }

  /**
   * @todo Implement testAugmentedSecond().
   */
  public function testAugmentedSecond()
  {
      // Remove the following lines when you implement this test.
      $this->markTestIncomplete(
        'This test has not been implemented yet.'
      );
  }

  /**
   * @todo Implement testDiminishedThird().
   */
  public function testDiminishedThird()
  {
      // Remove the following lines when you implement this test.
      $this->markTestIncomplete(
        'This test has not been implemented yet.'
      );
  }

  /**
   * @todo Implement testMinorThird().
   */
  public function testMinorThird()
  {
      // Remove the following lines when you implement this test.
      $this->markTestIncomplete(
        'This test has not been implemented yet.'
      );
  }

  /**
   * @todo Implement testMajorThird().
   */
  public function testMajorThird()
  {
      // Remove the following lines when you implement this test.
      $this->markTestIncomplete(
        'This test has not been implemented yet.'
      );
  }

  /**
   * @todo Implement testAugmentedThird().
   */
  public function testAugmentedThird()
  {
      // Remove the following lines when you implement this test.
      $this->markTestIncomplete(
        'This test has not been implemented yet.'
      );
  }

  /**
   * @todo Implement testDiminishedFourth().
   */
  public function testDiminishedFourth()
  {
      // Remove the following lines when you implement this test.
      $this->markTestIncomplete(
        'This test has not been implemented yet.'
      );
  }

  /**
   * @todo Implement testPerfectFourth().
   */
  public function testPerfectFourth()
  {
      // Remove the following lines when you implement this test.
      $this->markTestIncomplete(
        'This test has not been implemented yet.'
      );
  }

  /**
   * @todo Implement testAugmentedFourth().
   */
  public function testAugmentedFourth()
  {
      // Remove the following lines when you implement this test.
      $this->markTestIncomplete(
        'This test has not been implemented yet.'
      );
  }

  /**
   * @todo Implement testDiminishedFifth().
   */
  public function testDiminishedFifth()
  {
      // Remove the following lines when you implement this test.
      $this->markTestIncomplete(
        'This test has not been implemented yet.'
      );
  }

  /**
   * @todo Implement testPerfectFifth().
   */
  public function testPerfectFifth()
  {
      // Remove the following lines when you implement this test.
      $this->markTestIncomplete(
        'This test has not been implemented yet.'
      );
  }

  /**
   * @todo Implement testAugmentedFifth().
   */
  public function testAugmentedFifth()
  {
      // Remove the following lines when you implement this test.
      $this->markTestIncomplete(
        'This test has not been implemented yet.'
      );
  }

  /**
   * @todo Implement testDiminishedSixth().
   */
  public function testDiminishedSixth()
  {
      // Remove the following lines when you implement this test.
      $this->markTestIncomplete(
        'This test has not been implemented yet.'
      );
  }

  /**
   * @todo Implement testMinorSixth().
   */
  public function testMinorSixth()
  {
      // Remove the following lines when you implement this test.
      $this->markTestIncomplete(
        'This test has not been implemented yet.'
      );
  }

  /**
   * @todo Implement testMajorSixth().
   */
  public function testMajorSixth()
  {
      // Remove the following lines when you implement this test.
      $this->markTestIncomplete(
        'This test has not been implemented yet.'
      );
  }

  /**
   * @todo Implement testDiminishedSeventh().
   */
  public function testDiminishedSeventh()
  {
      // Remove the following lines when you implement this test.
      $this->markTestIncomplete(
        'This test has not been implemented yet.'
      );
  }

  /**
   * @todo Implement testMinorSeventh().
   */
  public function testMinorSeventh()
  {
      // Remove the following lines when you implement this test.
      $this->markTestIncomplete(
        'This test has not been implemented yet.'
      );
  }

  /**
   * @todo Implement testMajorSeventh().
   */
  public function testMajorSeventh()
  {
      // Remove the following lines when you implement this test.
      $this->markTestIncomplete(
        'This test has not been implemented yet.'
      );
  }

  /**
   * @todo Implement testMinorNinth().
   */
  public function testMinorNinth()
  {
      // Remove the following lines when you implement this test.
      $this->markTestIncomplete(
        'This test has not been implemented yet.'
      );
  }

  /**
   * @todo Implement testMajorNinth().
   */
  public function testMajorNinth()
  {
      // Remove the following lines when you implement this test.
      $this->markTestIncomplete(
        'This test has not been implemented yet.'
      );
  }

  /**
   * @todo Implement testAugmentedNinth().
   */
  public function testAugmentedNinth()
  {
      // Remove the following lines when you implement this test.
      $this->markTestIncomplete(
        'This test has not been implemented yet.'
      );
  }

  /**
   * @todo Implement testPerfectEleventh().
   */
  public function testPerfectEleventh()
  {
      // Remove the following lines when you implement this test.
      $this->markTestIncomplete(
        'This test has not been implemented yet.'
      );
  }

  /**
   * @todo Implement testAugmentedEleventh().
   */
  public function testAugmentedEleventh()
  {
      // Remove the following lines when you implement this test.
      $this->markTestIncomplete(
        'This test has not been implemented yet.'
      );
  }

  /**
   * @todo Implement testMinorThirteenth().
   */
  public function testMinorThirteenth()
  {
      // Remove the following lines when you implement this test.
      $this->markTestIncomplete(
        'This test has not been implemented yet.'
      );
  }

  /**
   * @todo Implement testMajorThirteenth().
   */
  public function testMajorThirteenth()
  {
      // Remove the following lines when you implement this test.
      $this->markTestIncomplete(
        'This test has not been implemented yet.'
      );
  }

  /**
   * @todo Implement testGetInterval().
   */
  public function testGetInterval()
  {
      // Remove the following lines when you implement this test.
      $this->markTestIncomplete(
        'This test has not been implemented yet.'
      );
  }

  /**
   * @dataProvider measureProvider
   */
  public function testMeasure($note1, $note2, $expected)
  {
    $result = ZeninoIntervalToolkit::measure($note1, $note2);
    $this->assertEquals($expected, $result);
    $this->assertInternalType('int', $result);
  }
  
  public function measureProvider()
  {
    return array(
      array('C', 'Bb', 10), array('A#', 'Cb', 1), array('B##', 'Ebb', 1),
      array('Gbb', 'A##', 6), array('E', 'Fb', 0)
    );
  }

  /**
   * @todo Implement testInvert().
   */
  public function testInvert()
  {
      // Remove the following lines when you implement this test.
      $this->markTestIncomplete(
        'This test has not been implemented yet.'
      );
  }

  /**
   * @todo Implement testDetermine().
   */
  public function testDetermine()
  {
      // Remove the following lines when you implement this test.
      $this->markTestIncomplete(
        'This test has not been implemented yet.'
      );
  }

  /**
   * @todo Implement testFromShortHand().
   */
  public function testFromShortHand()
  {
      // Remove the following lines when you implement this test.
      $this->markTestIncomplete(
        'This test has not been implemented yet.'
      );
  }
}
?>
