<?php
require_once dirname(__FILE__).'/../../ZeninoLoader.php';
ZeninoLoader::register();

/**
 * Test class for LfmArrayUtil.
 * Generated by PHPUnit on 2010-12-30 at 17:51:46.
 */
class LfmArrayUtilTest extends PHPUnit_Framework_TestCase
{
  /**
   * Sets up the fixture, for example, opens a network connection.
   * This method is called before a test is executed.
   */
  protected function setUp()
  {
  }

  /**
   * Tears down the fixture, for example, closes a network connection.
   * This method is called after a test is executed.
   */
  protected function tearDown()
  {
  }

  /**
   * @dataProvider rotateProvider
   */
  public function testRotate($array, $offset, $expected)
  {
    $result = LfmArrayUtil::rotate($array, $offset);
    $this->assertEquals($expected, $result);
  }
  public function rotateProvider()
  {
    $a = range(1,10);
    return array(
      array($a, 2, array(3,4,5,6,7,8,9,10,1,2)),
      array($a, 5, array(6,7,8,9,10,1,2,3,4,5)),
      array($a, 15, array(6,7,8,9,10,1,2,3,4,5)),
      array($a, 10,array(1,2,3,4,5,6,7,8,9,10)),
      array($a, -2, array(9,10,1,2,3,4,5,6,7,8)),
      array($a, -12, array(9,10,1,2,3,4,5,6,7,8)),
    );
  }

}
?>
